// Code generated by goctl. DO NOT EDIT.
package types

type AddDomainReq struct {
	Domain string `json:"domain"  validate:"required"`
	Email  string `json:"email"  validate:"required"`
}

type CertificateRequest struct {
	Id uint64 `json:"id"`
}

type AddOrRenewCertificateResp struct {
}

type CertSyncReq struct {
	Maximum uint64 `form:"maximum"`
}

type CertSyncResp struct {
	Certs []Cert `json:"certs"`
}

type Cert struct {
	Domain      string `json:"domain"`
	Certificate string `json:"certificate"`
	PrivateKey  string `json:"private_key"`
}

type UserLoginReq struct {
	Name string `json:"name"  validate:"required,email"`
	Pass string `json:"pass"  validate:"required"`
}

type UserLoginResp struct {
	Token string `json:"token"`
}
