// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	cert "github.com/pygzfei/issuer-gateway/issuer/internal/handler/cert"
	user "github.com/pygzfei/issuer-gateway/issuer/internal/handler/user"
	"github.com/pygzfei/issuer-gateway/issuer/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: user.UserLoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/user"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Authorization},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/domain",
					Handler: cert.AddDomainHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/cert",
					Handler: cert.AddCertHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/cert/upload",
					Handler: cert.AddCertFormUploadHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/cert",
					Handler: cert.RenewCertHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/certs",
					Handler: cert.GetCertsPagingHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api"),
	)
}
